#!/usr/bin/env python3
"""Find comma splices in the paper's prose, and say where each one is.

C1 in the quality backlog asked for a manual read-through of roughly sixty-seven
candidate sites. The list that produced that number was generated by a session
that never committed it, so the number outlived its evidence -- the same defect
this repository keeps finding in itself. This script regenerates the list from
the manuscript, so the next person does not inherit a count they cannot check.

A comma splice is two independent clauses joined by a comma alone. The test here
is structural rather than lexical: split the sentence at each comma, parse the
text on each side on its own, and flag the comma when *both* sides parse as an
independent clause -- a finite verb with its own nominal subject -- and the right
side does not open with a coordinating conjunction or a subordinator.

It reports candidates, not verdicts. Parsers mistake appositives and elliptical
constructions for clauses, and English tolerates the splice in a few settled
places. Every hit needs a human. What the script buys is that the human reads
twenty lines instead of eighteen pages.

**Calibrated, because an uncalibrated instrument reporting zero is worth nothing.**
`--selftest` runs twenty labelled sentences through the detector: eight genuine
splices and twelve legitimate commas drawn from this manuscript's own habits.
Measured 7/8 recall and 1/12 false alarms with `en_core_web_sm`. The miss is a
fragment the small parser reads as a noun pile rather than a clause; the false
alarm is a mid-sentence parenthetical. So a report of zero here means "none of
the shape this detector sees", and a careful reader is still owed a read-through.

Usage: python3 check_splices.py [--tex crossaudit.tex] [--json out.json]
       python3 check_splices.py --selftest
"""
from __future__ import annotations
import argparse, json, re, subprocess, sys
from pathlib import Path

import spacy

# Openers that make the following clause subordinate or coordinate, so the comma
# before them is doing legitimate work.
SUBORD = {
    "and", "but", "or", "nor", "for", "so", "yet",           # coordinating
    "because", "although", "though", "while", "whereas",     # subordinating
    "if", "unless", "since", "when", "whenever", "where",
    "after", "before", "until", "as", "than", "whether",
    "which", "who", "whom", "whose", "that",                 # relative
}


def prose(tex: Path) -> str:
    """Body text with maths, citations, tables and macros removed."""
    src = tex.read_text()
    src = re.sub(r"(?m)^\s*%.*$", "", src)
    # Drop float bodies wholesale: their contents are not prose.
    for env in ("figure", "table", "tabular", "center", "tikzpicture", "thebibliography"):
        src = re.sub(rf"\\begin{{{env}\*?}}.*?\\end{{{env}\*?}}", " ", src, flags=re.S)
    src = re.sub(r"\$[^$]*\$", " NUM ", src)
    src = re.sub(r"\\(cite|ref|label|eqref|url|footnote)\w*\{[^}]*\}", " ", src)
    out = subprocess.run(["pandoc", "-f", "latex", "-t", "plain", "--wrap=none"],
                         input=src, capture_output=True, text=True)
    return out.stdout if out.returncode == 0 else re.sub(r"\\[a-zA-Z]+\*?", " ", src)


# A real splice in academic prose almost always opens its second clause with an
# explicit subject: a pronoun, or a demonstrative with its noun. Restricting to
# that shape is what separates a usable list from a list of appositives and serial
# commas. It trades recall for a precision the reader will actually act on; the
# first version of this script flagged fifty-nine sites of which most were
# "component-level, checklist-aligned" and "a second vendor, a rulebook, scripts".
OPENERS = {"it", "they", "this", "these", "those", "we", "he", "she", "there",
           "that", "such", "one", "each", "both", "its", "their", "our",
           "the", "a", "an"}   # a determiner opener needs the verb test to earn its keep


def independent(nlp, text: str, require_explicit_subject: bool) -> bool:
    """True when the fragment stands alone as a clause.

    `require_explicit_subject` is set for the right-hand side: the subject must be
    a real token sitting before its verb, which excludes imperatives ("read the
    inputs") and the verb-phrase continuations that make up serial lists. The left
    side is held to a weaker test -- a finite verb, and no subordinator at the
    front -- because a small parser reads short fragments like "Determinism runs
    first" as a noun pile, and demanding a detected subject on both sides costs
    more recall than the precision is worth.
    """
    text = text.strip().strip(",;:")
    if len(text.split()) < 3:
        return False
    if not require_explicit_subject:
        head = re.match(r"[\"'(]*([A-Za-z]+)", text)
        if head and head.group(1).lower() in SUBORD:
            return False    # a fronted subordinate clause is not independent
    doc = nlp(text if text.endswith(".") else text + ".")
    for tok in doc:
        if tok.pos_ not in ("VERB", "AUX"):
            continue
        # A subject often attaches to the lexical verb rather than to the auxiliary
        # that carries the tense ("it does not eliminate", "these cannot be waived").
        # Accept the clause when tense lives anywhere in the verb group.
        finite = (tok.morph.get("VerbForm") in ([], ["Fin"])
                  or any(c.dep_ in ("aux", "auxpass") and c.morph.get("VerbForm") in ([], ["Fin"])
                         for c in tok.children))
        if not finite:
            continue
        subs = [c for c in tok.children if c.dep_ in ("nsubj", "nsubjpass")]
        if not require_explicit_subject:
            return True     # a finite verb is enough on the left
        if not subs:
            continue
        # The subject must sit at the very front of the fragment. Without this, any
        # relative clause later in the sentence ("a supervision protocol ... that
        # together specify a history") satisfies the test, and every appositive in
        # the paper is reported as a splice. A real splice puts its subject
        # immediately after the comma.
        if not any(c.i <= 2 and c.i < tok.i and c.pos_ in ("PRON", "NOUN", "PROPN")
                   for c in subs):
            continue
        return True
    return False


def serial(s: str, at: int) -> bool:
    """A comma inside an x, y, and z list is not a splice."""
    return bool(re.search(r",\s+(and|or|nor)\s", s[at:]))


def splices(nlp, text: str):
    for sent in nlp(text).sents:
        s = sent.text.strip()
        if len(s) < 25:
            continue
        for m in re.finditer(r",\s+", s):
            left, right = s[:m.start()], s[m.end():]
            first = re.match(r"[\"'(]*([A-Za-z]+)", right)
            if not first:
                continue
            word = first.group(1).lower()
            if word in SUBORD or word not in OPENERS:
                continue
            if serial(s, m.start()):
                continue
            if independent(nlp, left, False) and independent(nlp, right, True):
                yield {"sentence": s, "before": left[-70:], "after": right[:70]}
                break     # one report per sentence is enough to send someone to it


# Labelled fixtures. Splices first, then commas that are doing real work.
FIXTURES = [
    (True,  "The corpus was not clean, it drew three findings on the first pass."),
    (True,  "The auditor stated the constant correctly, its multiplication was still wrong."),
    (True,  "We adopted the findings in full, they were all correct."),
    (True,  "The rule required disclosure, the failure was never omission."),
    (True,  "Cross-vendor pairing dilutes bias, it does not eliminate correlated error."),
    (True,  "The ledger records the verdict, this is what makes replay possible."),
    (True,  "Determinism runs first, these checks cannot be waived by a model."),
    (True,  "The key was public from registration, our blinding claim does not survive."),
    (False, "Under the adjudicated map, with corrections logged, it scores 43 of 43."),
    (False, "The second arm was fresh-context subagents, one per increment, with no shared memory."),
    (False, "For everything not mechanisable, it is the human who reads the advisory trail."),
    (False, "The ingredients are plain: a second vendor, a rulebook, and scripts that run first."),
    (False, "Because the corpus is synthetic, it cannot support a claim about domain competence."),
    (False, "The auditor quoted the constant, read the inputs, and misevaluated the product."),
    (False, "This is a component-level, checklist-aligned trial on template-generated data."),
    (False, "When the seal is committed, the operator must be able to name its digest."),
    (False, "This was our mistake, a mis-pathed ignore rule, and the key is derivable anyway."),
    (False, "The report and our dispositions are committed at audits, a directory in the repo."),
    (False, "Although the arm scored well, its chance floor was high."),
    (False, "If the digest does not match, the workflow refuses to run."),
]


def selftest(nlp) -> int:
    tp = fn = fp = tn = 0
    for label, sent in FIXTURES:
        got = bool(list(splices(nlp, sent)))
        if label and got: tp += 1
        elif label: fn += 1; print(f"  missed: {sent}")
        elif got: fp += 1; print(f"  false alarm: {sent}")
        else: tn += 1
    print(f"\nrecall {tp}/{tp+fn} · false alarms {fp}/{fp+tn}")
    print("These are the rates any count this script prints should be read against.")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", default="crossaudit.tex")
    ap.add_argument("--json")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()

    nlp = spacy.load("en_core_web_sm")
    if a.selftest:
        return selftest(nlp)
    hits = list(splices(nlp, prose(Path(a.tex))))
    for i, h in enumerate(hits, 1):
        print(f"\n[{i}] …{h['before'].strip()} ⟨,⟩ {h['after'].strip()}…")
    print(f"\n{len(hits)} candidate splice(s). Each needs a human: a full stop, a "
          f"conjunction, or a decision that it reads correctly as written.")
    if a.json:
        Path(a.json).write_text(json.dumps(hits, indent=1) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
